---
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended

plugins:
  - react
  - react-hooks

parser: "@babel/eslint-parser"

globals:
  page: true
  browser: true
  context: true
  jestPuppeteer: true
  BASE_URL: true

rules:
  # Code quality rules
  no-unused-vars: ["error", { "argsIgnorePattern": "^_", "destructuredArrayIgnorePattern": "^_" }]
  react/prop-types: off # Remove this override once all props have been typed using PropTypes or TypeScript.

  # Code style rules

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    modules: true

env:
  es6: true
  browser: true
  node: true
  jest: true

settings:
  react:
    version: detect
