language: node_js
sudo: false
node_js:
  - "9"
install:
  - npm install
  - pip install --user awscli
script:
  - npm run build
after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "release" ]]; then
      npm run gzip-and-upload;
      npm run redeploy-site;
    fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
      npm run rebuild-docker-image;
    fi
notifications:
  email:
    on_success: never
    on_failure: always
