language: node_js
sudo: false
node_js:
  - "9"
install:
  - npm install
script:
  - npm run build
after_success:
  - test $TRAVIS_BRANCH = "prerelease" && npm run redeploy-site  
notifications:
  email:
    on_success: never
    on_failure: always
