name: "Make PRs for Nextstrain projects which depend on Auspice"
on:
  workflow_dispatch:
jobs:
  make-pr-on-nextstrain-dot-org:
    uses: ./.github/workflows/make_pr_for_downstream_repo.yaml
    secrets: inherit
    with:
      repository: nextstrain/nextstrain.org
