name: "Preview on downstream repo"
on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      directory:
        required: false
        type: string
        default: .

# Cancel any in-progress runs of a caller workflow on the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      DESTINATION_REPO_DIR: repo

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Checkout downstream repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          path: ${{ env.DESTINATION_REPO_DIR }}
          token: ${{ secrets.GH_TOKEN_NEXTSTRAIN_BOT_REPO }}

      - name: Install Auspice from PRs HEAD commit
        shell: bash
        working-directory: ${{ env.DESTINATION_REPO_DIR }}/${{ inputs.directory }}
        run: |
          npm ci
          npm install nextstrain/auspice#${{ github.sha }}
          git add package.json package-lock.json

          git config user.name "nextstrain-bot"
          git config user.email "nextstrain-bot@users.noreply.github.com"
          git commit --message="[testing only] Upgrade Auspice to ${{ github.sha }}"

      - name: Create Pull Request
        working-directory: ${{ env.DESTINATION_REPO_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_NEXTSTRAIN_BOT_REPO }}
          title: '[bot] [DO NOT MERGE] Test Auspice PR ${{ github.event.number }}'
          body: |
            This PR has been created to test this project running Auspice with changes from https://github.com/nextstrain/auspice/pull/${{ github.event.number }}.

            Note that Auspice has been installed with changes from both the PR's source and target branches.
            This will surface any issues that can arise from merging the PR in Auspice. To address these issues locally, update the source branch (e.g. with a git rebase).

            This message and corresponding commits were automatically created by a GitHub Action from [nextstrain/auspice](https://github.com/nextstrain/auspice).
        run: |
          branch="nextstrain-bot/test-auspice-pr/${{ github.event.number }}"
          git switch -c "$branch"
          git push --force origin HEAD
          pr_url=$(gh pr list --head "$branch" --json url | jq -r '.[0].url')

          if [ "$pr_url" = "null" ]; then
            pr_url="$(gh pr create --title "$title" --body "$body" --draft)"
            echo "Pull request created: $pr_url" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "Pull request updated: $pr_url" >> "$GITHUB_STEP_SUMMARY"
          fi
